// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxrofexvojymhnaunbft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cm9mZXh2b2p5bWhuYXVuYmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTY0NjIsImV4cCI6MjA3MTg5MjQ2Mn0.wHsQv93yKVJCZRg5gJh6qfFd2Co1YYeAoV_U3oOgTWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});